name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: List generated files
        run: ls -R dist

      - name: Commit and push SVGs to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git checkout --orphan output
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Update Pac-Man graph"
          git push -f origin output
